// frontend/src/App.jsx
import React from 'react';

import Navigation from "./Navigation";
import Signature from "./Signature";
import Sky from './Sky';
import System from './System';

import './css/App.css';

export default class App extends React.Component {
  render() {
    return (
      <div id='index'>
        <Sky stars={1000} tick={20} />
        <h1 onClick={redirectToGithub}>Samuel Lando</h1>
        <System planets={1} />
        <Navigation />
        <Signature emoji="❤️" by="Sam" onClick={redirectToGithub} />
      </div>
    );
  }
}

function redirectToGithub() {
  window.location.href = "https://github.com/samuellando";
}

// src/components/view/App.vue
<template>
  <div id="app">
    <div class="homeContainer">
      <Sky :stars="500" />
      <Heading text="Samuel Lando" />
      <System :planets="3" />
      <Links/>
      <Signature text="Made with ♥ by Sam"/>
    </div>
  </div>
</template>

<script src="@/components/viewmodel/App.js"></script>
<style src="@/components/view/stylesheets/App.css"></style>
